name: Check formatting

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93
        with:
          otp-version: "25.3"
          rebar3-version: "3.22"
      - run: rebar3 as dialyzer dialyzer
